language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ryurikk/docker-react . 

script:
  - docker run -e CI=true ryurikk/docker-react npm run test -- --coverage